# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
 region  = "AWS_ACCOUNT_ID"
 #profile = "default"
  
assume_role {
    session_name = "terraform"
    role_arn = "arn:aws:iam::AWS_ACCOUNT_ID:role/terraform-assumed-role-shared"
  }
}

