# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-ppd-state"
    dynamodb_table = "terraform-ppd-lock-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ap-south-1"
    role_arn       = "arn:aws:iam::ACCOUNT_ID:role/terraform-assumed-role-shared"
  }
}
